### ISSUE TITLE
Test `display_list::test::test_multi_threaded_display_list_search` fails randomly

### ISSUE THREAD

**Issue by marioortizmanero** [messense/mupdf-rs#26] opened 2021-04-24 10:02 UTC
On my machine (Linux 5.11.15-arch1-2) there's a test that does fail randomly:

```
failures:

---- display_list::test::test_multi_threaded_display_list_search stdout ----
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/display_list.rs:194:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/display_list.rs:194:21
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/display_list.rs:194:21
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/display_list.rs:194:21
thread 'display_list::test::test_multi_threaded_display_list_search' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/display_list.rs:200:10


failures:
    display_list::test::test_multi_threaded_display_list_search
```

_Originally posted by @marioortizmanero in https://github.com/messense/mupdf-rs/issues/25#issuecomment-826067409_

**Comment by Bobo1239** [comment] 2021-08-12 20:51
Spent some time debugging this today and afaict we're either handling MuPDF contexts incorrectly (though I couldn't tell what we're doing wrong) or it's a MuPDF bug. I've opened a bug report upstream to ask for assistance: https://bugs.ghostscript.com/show_bug.cgi?id=704212

**Comment by Bobo1239** [comment] 2021-08-13 15:12
The bug is now fixed [upstream](http://git.ghostscript.com/?p=mupdf.git;a=commit;h=0110a6bd194bc48c435450963ffffdf65c14204b) and I've also confirmed that our test passes with that patch. It also passes in my Mac OSX VM so we can remove that `#[cfg(not(target_os = "macos"))]`.

The only question now is whether to wait for a new mupdf release (don't know about their release schedule) or to track their master branch. (would need to switch to their [canonical repository](http://git.ghostscript.com/?p=mupdf.git;a=summary) since the [github mirror](https://github.com/ArtifexSoftware/mupdf) seems out of date)

**Comment by messense** [comment] 2021-08-13 15:20
Great! Let's track their master branch instead.

**Closed** 2021-08-14 04:50 UTC
Labels: bug
